var questions = [
  'Who inspires you?, Who do you aspire to be like?',
  'What was the last book you read without skipping through anything?',
  'What is the weirdest scar you have and how did you get it?',
  'What is the most random thing you’ve ever watched all the way through on Netflix?',
  'If you could trade lives with one person for an entire day who would it be and why?',
  'Do you believe in ghosts?',
  'Shark diving, bungee jumping, or sky diving?',
  'Which would be harder for you to give up: coffee or alcohol?',
  'How did you meet your best friend?',
  'Do you have a sweet tooth or a savory tooth?',
  'What is something you’ve always wanted to try but have been too scared to?',
  'What accomplishments are you most proud of?',
  'If you were going to go to the movies alone, what would be the perfect film for you to watch by yourself?',
  'What is your favorite Wikipedia article?',
  'What is your favorite physical attribute about yourself?',
  'Tell me about the best vacation you’ve ever taken',
  'Where is your favorite place to go on a weekday afternoon when you have no plans or obligations?',
  'What is one of the weirdest things you used to do as a teenager?',
  'Gin, vodka, or tequila?',
  'What drives you to do what you do? What motivates you?',
  'In your opinion, what is the best Disney movie to come out since Disney’s Golden Age?',
  'What kind of phone was your first cell phone?',
  'What did you love most about the place you grew up? What about it did you love the least?',
  'What trajectory are you hoping to push yourself onto? Where do you want to head?',
  'What is your most bizarre talent?',
  'Is there a documentary or book that really changed the way you thought about something?',
  'What are three albums (soundtracks or compilations don’t count) that really define you or have shaped you as a person?',
  'Who was someone you really looked up to when you were little — someone you considered to be a mentor?',
  'What’s your favorite cheesy pick-up line? Have you ever used it for real?',
  'Who is a character from a TV show or a book that you’ve always resonated with?',
  'Can I get you another drink?',
  'What movie deserves a sequel?',
  'What one toy would you like to throw repeatedly at a brick wall?',
  'What is one thing a woman should never do?',
  'Who would you hate to see naked?',
  'What is your favorite kind of cereal?',
  'What is one thing you always wanted as a kid, but never got?',
  'If you were in a witness protection program, what would be your alias?',
  'What is the nicest thing someone else has done for you?',
  'If you could bring someone famous back from the grave, who would you choose?',
  'Where do you not mind waiting?',
  'If you could lock up one person in a mental institution, who would it be?',
  'What is your favorite potato chip flavor?',
  'If you could project yourself into the past, were would you go?',
  'What is your most impressive car repair skill?',
  'What is the best sports stadium/arena you have been to?',
  'What would you refuse to do for one million dollars?',
  'If you were home on a rainy Sunday afternoon, what movie would you want to see on television?',
  'What historical figure would you most like to have a discussion with?',
  'If you could close one fast food chain, due to disgusting food, what would you pick?',
  'What is one thing you refuse to share?',
  'If you went to a psychiatrist, what would he/she say you suffer from?',
  'If you could be on the cover of any magazine, what would you choose?',
  'What makes you really sleepy?',
  'What one thing annoys you most at a restaurant?',
  'What do people do too much of today?',
  'What is the most inspiring movie you have ever seen?',
  'What household chore have you never done?',
  'How do you like to relax?',
  'In what part of the world would you hate to be by yourself?',
  'To what would you like to devote more time?',
  'What would be the best thing about not having a sense of smell?',
  'Where would you not go back to for a vacation?',
  'What is the scariest scene you remember from a kid\'s movie?',
  'If you could dis-invent one thing, what would it be?',
  'What always makes you a more confident person?',
  'What is the greatest pain you have ever suffered?',
  'If you could buy one object to complete your home, what would it be?',
  'What was your favorite childhood game?',
  'Who is the most famous person you have ever met?',
  'If fat, calories, cholesterol, etc were not an issue, what two foods would you feast on?',
  'If you could be a member of any TV-sitcom family, which would it be?',
  'What is your favorite movie line or scene?',
  'What part of your body could use a little lotion?',
  'What language would you like to master?',
  'If you were directing a movie, who would you cast as your leading man and woman?',
  'Aside from lettuce, what are your two favorite salad ingredients?',
  'If you had to dispose of a dead body, how would you do it?',
  'Do you have a place where you would like to go and think? If so, where?',
  'What is your favorite event in the Winter Olympics?',
  'What profession have you always admired?'
];

$(document).ready(function() {
  $('#testing').click(function() {
    var random = Math.floor(Math.random() * 6) + 1;
    // alert(questions[random]);
    $('#question-view').text(questions[random]);
  });
});
